---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  ports:
    - port: 3306
  ##
  # Create service selector labels here
  selector:
    app: wordpress
    tier: myasql
  ##
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-mysql
data:
  ##
  # create non-sensative data attributes
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wordpress_user
  ##
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  ##
  # Create app label selectors here
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  ##
  template:
    ##
    # Create metadata labels here
    metadata:
      labels:
        app: wordpress
        tier: mysql
    ##
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        ##
        # mount non-sensitive environment vars from configmap
        # MYSQL_DATABASE | MYSQL_USER
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: wordpress-mysql
              key: database
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: wordpress-mysql
              key: user
        ##
        ##
        # mount sensitive environment vars from secret
        # MYSQL_ROOT_PASSWORD | MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: user-password
        ##
        ports:
        - containerPort: 3306
          name: mysql
      ##
      # define volume mounts here, be sure to reference
      # the PVC in your container spec
      spec:
        containers:
        - name: mysql
          image: mysql:8.0
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
        volumes:
        - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-mysql-pvc
      ##
---
##
# Create persistent volume claim here
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
##
