---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  ports:
    - port: 80
  ##
  # Create service selector labels here
  selector:
    app: wordpress
    tier: frontend
  ##
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress
data:
  ##
  # create non-sensative data attributes
    WORDPRESS_DB_HOST: wordpress-mysql
    WORDPRESS_DB_USER: wordpress
    WORDPRESS_DB_PASSWORD: ${database.user-password}
  ##
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  replicas: 3
  ##
  # Create app selector labels here
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  ##
  template:
    ##
    # Create metadata labels here
    metadata:
      labels:
        app: wordpress
        tier: frontend
    ##
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        env:
        ##
        # mount non-sensitive environment vars from configmap ref
        # WORDPRESS_DB_HOST | WORDPRESS_DB_USER
        ##
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wordpress
              key: host
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: wordpress
              key: user
        ##
        # mount sensitive environment vars from secret ref
        # WORDPRESS_DB_PASSWORD (hint use the user-password key)
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database
              key: user-password
        ##
        ports:
        - containerPort: 80
          name: wordpress
      ##
      # define volume mounts here, be sure to reference
      # the PVC in your container spec
      spec:
        containers:
        - name: mysql
          image: mysql:8.0
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
        volumes:
        - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-mysql-pvc
      ##
---
##
# Create persistent volume claim here
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
##
